version: "3"
services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - order-service-network

  order-service-db-mongodb:
    image: mongo
    container_name: order-service-mongodb
    ports:
      - "27017:27017"
    networks:
      - order-service-network

networks:
  order-service-network:
    external: false