# Server props
server:
  port: 8080
  #servlet:
    #context-path: /api

# Server Monitoring props
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Database props
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Security
jwt:
  secret: userservice
  issuer: "Sales Order System"
  tokenValidity: 18000 # (5 * 60 * 60)